apiVersion: v1
kind: Namespace
metadata:
  name: istio-gateways
  labels:
    istio-operator-managed: Reconcile
    istio.io/rev: asm-1-17
---
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: default-bjdazure-tech-gw
  namespace: istio-gateways
spec:
  selector:
    istio: aks-istio-ingressgateway-internal  
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*.bjdazure.tech"
  - port:
      number: 80
      name: http-serving
      protocol: HTTP
    hosts:
    - "*.knative.bjdazure.tech"
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name:  default-bjdazure-tech-vs
  namespace: istio-gateways
spec:
  hosts:
  -  istio-default.bjdazure.tech
  gateways:
  -  istio-gateways/default-bjdazure-tech-gw
  http:
  - route:
    - destination:
        host: default-backend-svc
        port:
          number: 80
  
