apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-ingress-sa-identity
  namespace: aks-istio-ingress
  annotations:
    azure.workload.identity/client-id: d335296d-f4ae-442a-8809-6861b3521082
    azure.workload.identity/tenant-id: 16b3c013-d300-468d-ac64-7eda0820b6d3
  labels:
    azure.workload.identity/use: "true"