apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-ingress-sa-identity
  namespace: aks-istio-ingress
  annotations:
    azure.workload.identity/client-id: bd3f9d18-40eb-43ba-a8b1-1178535af662
    azure.workload.identity/tenant-id: 16b3c013-d300-468d-ac64-7eda0820b6d3
  labels:
    azure.workload.identity/use: "true"