apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-ingress-sa-identity
  namespace: aks-istio-ingress
  annotations:
    azure.workload.identity/client-id: 6d10cb9d-c2a5-4ec7-ac3e-5d4d59eb452a
    azure.workload.identity/tenant-id: 16b3c013-d300-468d-ac64-7eda0820b6d3
  labels:
    azure.workload.identity/use: "true"