apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-ingress-sa-identity
  namespace: aks-istio-ingress
  annotations:
    azure.workload.identity/client-id: 0184a3cc-4212-4717-9b0e-b479c2d98c9f
    azure.workload.identity/tenant-id: 16b3c013-d300-468d-ac64-7eda0820b6d3
  labels:
    azure.workload.identity/use: "true"