apiVersion: v1
kind: ServiceAccount
metadata:
  name: istio-ingress-sa-identity
  namespace: aks-istio-ingress
  annotations:
    azure.workload.identity/client-id: 53df8e51-61db-480a-bca3-7f043db11168
    azure.workload.identity/tenant-id: 16b3c013-d300-468d-ac64-7eda0820b6d3
  labels:
    azure.workload.identity/use: "true"